spring:
  application:
    name: library-service-java
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##LOCAL_GEFAMI
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8082
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.validator: DEBUG
    com.gefami.library: DEBUG